-- Execute este arquivo uma vez no SQL Editor do Supabase.
create table if not exists public.rankings (
  id bigint generated by default as identity primary key,
  ranking_date date not null,
  reset_slot text not null check (reset_slot in ('05', '18')),
  image_path text not null,
  image_url text not null,
  published_at timestamptz not null default now(),
  published_by uuid references auth.users(id),
  unique (ranking_date, reset_slot)
);

alter table public.rankings enable row level security;

drop policy if exists "Rankings public read" on public.rankings;
create policy "Rankings public read" on public.rankings for select to anon, authenticated using (true);
drop policy if exists "Admins insert rankings" on public.rankings;
create policy "Admins insert rankings" on public.rankings for insert to authenticated with check (auth.uid() = published_by);
drop policy if exists "Admins update rankings" on public.rankings;
create policy "Admins update rankings" on public.rankings for update to authenticated using (true) with check (auth.uid() = published_by);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('ranking-prints', 'ranking-prints', true, 10485760, array['image/png','image/jpeg','image/webp'])
on conflict (id) do update set public=true, file_size_limit=10485760, allowed_mime_types=array['image/png','image/jpeg','image/webp'];

drop policy if exists "Public ranking images" on storage.objects;
create policy "Public ranking images" on storage.objects for select to anon, authenticated using (bucket_id = 'ranking-prints');
drop policy if exists "Admins upload ranking images" on storage.objects;
create policy "Admins upload ranking images" on storage.objects for insert to authenticated with check (bucket_id = 'ranking-prints');
drop policy if exists "Admins update ranking images" on storage.objects;
create policy "Admins update ranking images" on storage.objects for update to authenticated using (bucket_id = 'ranking-prints') with check (bucket_id = 'ranking-prints');
